services:
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_storage:/qdrant/storage

  app:
    build: ./app
    ports:
      - "127.0.0.1:8888:8888"
    volumes:
      - ./app/work:/home/app/work
      - ./data:/data
    command: jupyter lab --ServerApp.ip=0.0.0.0 --ServerApp.port=8888 --ServerApp.open_browser=False --ServerApp.token=${JUPYTER_TOKEN} --ServerApp.allow_root=True
    env_file:
      - ./.env
    depends_on:
      - qdrant

volumes:
  qdrant_storage:
